### ISSUE TITLE
Two animations for the same element lead to unexpected behavior

### ISSUE THREAD

**Issue by Luar78** [bartbutenaers/node-red-contrib-ui-svg#119]
Hi. Here is the problem I have encountered. I have created two animations for a line "RailR2".
The first animation should do a running light to the right and the second animation a running light to the left by the attribute "stroke-dashoffset". 
![image](https://user-images.githubusercontent.com/15855472/227125030-66c905e2-0c26-4613-b64f-98c09f7f3f50.png)

![image](https://user-images.githubusercontent.com/15855472/227125118-756a24bf-5cb8-4b21-82ac-ca8e10b50c91.png)

If I start both animations by two input message, then the animations block each other and the line stops and does not move.
Although I send more "input message" to stop the animations and then to start them, I can't get the animations to run.
Apparently there is no way to check if a certain animation is active to stop it specifically before starting the opposite one.

I am currently using
node-red 3.0.2
node-red-dashboard 3.4.0
node-red-contrib-ui-svg 2.3.1

**Comment by Luar78** [comment]
Hello Bart.
I use Node Red to visualize the energy flow of my solar system in the RV. As a trigger, measured values from my Victron components are used which are integrated in Node Red. There are lines that move only in one direction or are off and there are lines (like the rail in the middle) that move to the left or right.

![image](https://user-images.githubusercontent.com/15855472/227442599-44f36d71-ec4e-49b2-b058-2606cb9b73a6.png)

The corresponding animation is started with infinite cycles. As soon as the measured values of the Victron components show a different flow, the animations are stopped accordingly and others are started.
Because of the different measured values, the calls to start and stop the animation overlapped. To avoid this problem I inserted a "Delay Block" which allows only one message per second to pass.
This makes the visualization less responsive, but at least there is no freez in the animation.

Raul.

**Comment by bartbutenaers** [comment]
Hi @Luar78,

Thanks for sharing your project.  That makes it much more clear.  Nice setup!
Yes indeed it might be better to aggregate the measurements, and inject messages to the svg at regular intervals like you do.

Did I understand correctly that this issue is solved?
Bart

**Comment by Luar78** [comment]
Hi @bartbutenaers.
The problem is not really solved, but I avoid it by reducing the number of messages.
Thank you very much.

Raul.
